"""
Batch Sandbox tab UI and execution engine module.
Modularized under `interface.batch`. This module forwards all exports for backward compatibility.
"""

from interface.batch import (
    TASK_CHOICES,
    TASK_FREE_ANNOTATION,
    TASK_RECLASSIFICATION,
    PipelineCancelledException,
    run_batch_detection_gui,
    run_batch_dispatcher,
    cancel_pipeline,
    render_status_table as _render_status_table,
    detections_to_yolo as _detections_to_yolo,
    classify_regions_gui,
    classify_region as _classify_region,
    crop_with_padding as _crop_with_padding,
    extract_regions as _extract_regions,
    draw_recls_bbox as _draw_recls_bbox,
    make_recls_client as _make_recls_client,
    render_recls_table as _render_recls_table,
    _RECLS_EMPTY_TABLE,
    _RECLS_PALETTE,
    on_explorer_image_change,
    on_explorer_round_change,
    on_explorer_prev,
    on_explorer_next,
    on_explorer_first,
    on_explorer_last,
    on_explorer_pos,
    navigate_batch_explorer,
    build_batch_tab as _build_batch_tab,
    toggle_run_btn,
    toggle_external_api,
    on_batch_preset_change,
    on_batch_strategy_change,
)

__all__ = [
    "TASK_CHOICES",
    "TASK_FREE_ANNOTATION",
    "TASK_RECLASSIFICATION",
    "PipelineCancelledException",
    "run_batch_detection_gui",
    "run_batch_dispatcher",
    "cancel_pipeline",
    "_render_status_table",
    "_detections_to_yolo",
    "classify_regions_gui",
    "_classify_region",
    "_crop_with_padding",
    "_extract_regions",
    "_draw_recls_bbox",
    "_make_recls_client",
    "_render_recls_table",
    "_RECLS_EMPTY_TABLE",
    "_RECLS_PALETTE",
    "on_explorer_image_change",
    "on_explorer_round_change",
    "on_explorer_prev",
    "on_explorer_next",
    "on_explorer_first",
    "on_explorer_last",
    "on_explorer_pos",
    "navigate_batch_explorer",
    "_build_batch_tab",
    "toggle_run_btn",
    "toggle_external_api",
    "on_batch_preset_change",
    "on_batch_strategy_change",
]
